In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:

# Assuming you have your data in a DataFrame named `credit`
# Example:
# credit = pd.read_csv('credit_data.csv')

# Drop rows where the target variable is NaN
credit = credit.dropna(subset=["Credit Score"])

# Separate features and target
X = credit.drop("Credit Score", axis=1)
y = credit["Credit Score"]

# Handle missing values in features using SimpleImputer
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)

# Create training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define models
linear_model = LinearRegression()
logistic_model = LogisticRegression(max_iter=10000)  # Increased max_iter for convergence
decision_tree_model = DecisionTreeClassifier()

# Train models
linear_model.fit(X_train, y_train)
logistic_model.fit(X_train, y_train)
decision_tree_model.fit(X_train, y_train)

# Define the new data point
new_data_point = {
    "Annual Income": 1000000,
    "Years in current job": 5,
}

# Convert new data point to DataFrame
new_data_point_df = pd.DataFrame([new_data_point])

# Ensure the new data point has the same columns as the training data
# Handle missing values in the new data point
new_data_point_df = imputer.transform(new_data_point_df)

# Predict credit score using each model
linear_model_prediction = linear_model.predict(new_data_point_df)[0]
logistic_model_prediction = logistic_model.predict(new_data_point_df)[0]
decision_tree_model_prediction = decision_tree_model.predict(new_data_point_df)[0]

# Print the predictions
print("Linear Model Prediction:", linear_model_prediction)
print("Logistic Regression Prediction:", logistic_model_prediction)
print("Decision Tree Prediction:", decision_tree_model_prediction)

In [ ]:
salary= pd.read_csv("/content/drive/MyDrive/salaries (1).csv")
salary

In [ ]:
salary.dtypes

company                  object
job                      object
degree                   object
salary_more_then_100k     int64
dtype: object

In [ ]:
salary.describe()

salary_more_then_100k
count                 16.000
mean                   0.625
std                    0.500
min                    0.000
25%                    0.000
50%                    1.000
75%                    1.000
max                    1.000

In [ ]:
#drop salary column
input = salary.drop("salary_more_then_100k", axis = "columns")
input

company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [ ]:
target =salary["salary_more_then_100k"]
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [ ]:
#convert input data to dummy variable
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [ ]:
input.head(2)

company              job     degree
0  google  sales executive  bachelors
1  google  sales executive    masters

In [ ]:
input["company_x"] = le_company.fit_transform(input["company"])
input["job_x"] =  le_company.fit_transform(input["job"])
input["degree_x"] =  le_company.fit_transform(input["degree"])

In [ ]:
#drop the inital columns (company, job and degree)
final_dummy = input.drop(["company", "job","degree"],axis = "columns")
final_dummy

company_x  job_x  degree_x
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [ ]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [ ]:
final_dummy

company_x  job_x  degree_x
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [ ]:
model = tree.DecisionTreeClassifier()
model

DecisionTreeClassifier()

In [ ]:
model.fit(final_dummy , target)

DecisionTreeClassifier()

In [ ]:
model.score(final_dummy , target)

1.0

In [ ]:
final_dummy

company_x  job_x  degree_x
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [ ]:
salary

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [ ]:
#is the salary of a google computer programmer with bachelor degree > 100k

In [ ]:
model.predict ([[2,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
#is the salary of a google computer programmer with master degree > 100k

In [ ]:
model.predict([[2,1,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
#is the salary of a facebook
#computer programmer with masters degree >100k
model.predict([[1,1,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
x

array([1])